#!/bin/bash

SRC="/c/laragon/www/testt/almalath.com"
DST="/c/laragon/www/almalatlar/resources/views"

apply_replacements() {
    local FILE="$1"
    local DEPTH="$2"

    if [ "$DEPTH" -eq 0 ]; then
        sed -i 's|href="wp-content/|href="/wp-content/|g' "$FILE"
        sed -i "s|href='wp-content/|href='/wp-content/|g" "$FILE"
        sed -i 's|src="wp-content/|src="/wp-content/|g' "$FILE"
        sed -i "s|src='wp-content/|src='/wp-content/|g" "$FILE"
        sed -i 's|url(wp-content/|url(/wp-content/|g' "$FILE"
        sed -i 's|href="wp-includes/|href="/wp-includes/|g' "$FILE"
        sed -i "s|href='wp-includes/|href='/wp-includes/|g" "$FILE"
        sed -i 's|src="wp-includes/|src="/wp-includes/|g' "$FILE"
        sed -i "s|src='wp-includes/|src='/wp-includes/|g" "$FILE"

    elif [ "$DEPTH" -eq 1 ]; then
        sed -i 's|href="../wp-content/|href="/wp-content/|g' "$FILE"
        sed -i "s|href='../wp-content/|href='/wp-content/|g" "$FILE"
        sed -i 's|src="../wp-content/|src="/wp-content/|g' "$FILE"
        sed -i "s|src='../wp-content/|src='/wp-content/|g" "$FILE"
        sed -i 's|href="../wp-includes/|href="/wp-includes/|g' "$FILE"
        sed -i "s|href='../wp-includes/|href='/wp-includes/|g" "$FILE"
        sed -i 's|src="../wp-includes/|src="/wp-includes/|g' "$FILE"
        sed -i "s|src='../wp-includes/|src='/wp-includes/|g" "$FILE"
        sed -i 's|href="wp-content/|href="/wp-content/|g' "$FILE"
        sed -i "s|href='wp-content/|href='/wp-content/|g" "$FILE"
        sed -i 's|src="wp-content/|src="/wp-content/|g' "$FILE"
        sed -i "s|src='wp-content/|src='/wp-content/|g" "$FILE"

    elif [ "$DEPTH" -eq 2 ]; then
        sed -i 's|href="../../wp-content/|href="/wp-content/|g' "$FILE"
        sed -i "s|href='../../wp-content/|href='/wp-content/|g" "$FILE"
        sed -i 's|src="../../wp-content/|src="/wp-content/|g' "$FILE"
        sed -i "s|src='../../wp-content/|src='/wp-content/|g" "$FILE"
        sed -i 's|href="../../wp-includes/|href="/wp-includes/|g' "$FILE"
        sed -i "s|href='../../wp-includes/|href='/wp-includes/|g" "$FILE"
        sed -i 's|src="../../wp-includes/|src="/wp-includes/|g' "$FILE"
        sed -i "s|src='../../wp-includes/|src='/wp-includes/|g" "$FILE"
        sed -i 's|href="../wp-content/|href="/wp-content/|g' "$FILE"
        sed -i "s|href='../wp-content/|href='/wp-content/|g" "$FILE"
        sed -i 's|src="../wp-content/|src="/wp-content/|g' "$FILE"
        sed -i "s|src='../wp-content/|src='/wp-content/|g" "$FILE"
        sed -i 's|href="wp-content/|href="/wp-content/|g' "$FILE"
        sed -i "s|href='wp-content/|href='/wp-content/|g" "$FILE"
        sed -i 's|src="wp-content/|src="/wp-content/|g' "$FILE"
        sed -i "s|src='wp-content/|src='/wp-content/|g" "$FILE"
    fi

    # Root-relative href links (double-quoted) - service sub-pages first
    sed -i 's|href="service/access-control-system/index.html"|href="/service/access-control-system"|g' "$FILE"
    sed -i 's|href="service/applications-development-services/index.html"|href="/service/applications-development-services"|g' "$FILE"
    sed -i 's|href="service/artificial-intelligence-ai/index.html"|href="/service/artificial-intelligence-ai"|g' "$FILE"
    sed -i 's|href="service/audio-visual-system/index.html"|href="/service/audio-visual-system"|g' "$FILE"
    sed -i 's|href="service/big-data/index.html"|href="/service/big-data"|g' "$FILE"
    sed -i 's|href="service/building-management-system/index.html"|href="/service/building-management-system"|g' "$FILE"
    sed -i 's|href="service/business-process-automation/index.html"|href="/service/business-process-automation"|g' "$FILE"
    sed -i 's|href="service/call-center-services/index.html"|href="/service/call-center-services"|g' "$FILE"
    sed -i 's|href="service/cctv-system/index.html"|href="/service/cctv-system"|g' "$FILE"
    sed -i 's|href="service/data-center-solutions-services/index.html"|href="/service/data-center-solutions-services"|g' "$FILE"
    sed -i 's|href="service/fire-alarm-fire-suspension-system/index.html"|href="/service/fire-alarm-fire-suspension-system"|g' "$FILE"
    sed -i 's|href="service/internet-of-things-iot/index.html"|href="/service/internet-of-things-iot"|g' "$FILE"
    sed -i 's|href="service/it-information-security/index.html"|href="/service/it-information-security"|g' "$FILE"
    sed -i 's|href="service/it-infrastructure-management/index.html"|href="/service/it-infrastructure-management"|g' "$FILE"
    sed -i 's|href="service/it-managed-services/index.html"|href="/service/it-managed-services"|g' "$FILE"
    sed -i 's|href="service/it-resource-outsourcing/index.html"|href="/service/it-resource-outsourcing"|g' "$FILE"
    sed -i 's|href="service/it-service-management/index.html"|href="/service/it-service-management"|g' "$FILE"
    sed -i 's|href="service/master-clock-system/index.html"|href="/service/master-clock-system"|g' "$FILE"
    sed -i 's|href="service/next-generation-data-centers/index.html"|href="/service/next-generation-data-centers"|g' "$FILE"
    sed -i 's|href="service/public-address-system/index.html"|href="/service/public-address-system"|g' "$FILE"
    sed -i 's|href="service/voice-over-ip-telephony-solutions-voip/index.html"|href="/service/voice-over-ip-telephony-solutions-voip"|g' "$FILE"
    sed -i 's|href="service/wireless-solutions/index.html"|href="/service/wireless-solutions"|g' "$FILE"
    sed -i 's|href="service/index.html"|href="/service"|g' "$FILE"
    sed -i 's|href="about/index.html"|href="/about"|g' "$FILE"
    sed -i 's|href="contact/index.html"|href="/contact"|g' "$FILE"
    sed -i 's|href="customers-clients/index.html"|href="/customers-clients"|g' "$FILE"
    sed -i 's|href="partners/index.html"|href="/partners"|g' "$FILE"
    sed -i 's|href="team-details/index.html"|href="/team-details"|g' "$FILE"
    sed -i 's|href="it-hardware-software/index.html"|href="/it-hardware-software"|g' "$FILE"
    sed -i 's|href="it-passive-equipment/index.html"|href="/it-passive-equipment"|g' "$FILE"
    sed -i 's|href="index.html"|href="/"|g' "$FILE"

    # Root-relative href links (single-quoted)
    sed -i "s|href='service/access-control-system/index.html'|href='/service/access-control-system'|g" "$FILE"
    sed -i "s|href='service/applications-development-services/index.html'|href='/service/applications-development-services'|g" "$FILE"
    sed -i "s|href='service/artificial-intelligence-ai/index.html'|href='/service/artificial-intelligence-ai'|g" "$FILE"
    sed -i "s|href='service/audio-visual-system/index.html'|href='/service/audio-visual-system'|g" "$FILE"
    sed -i "s|href='service/big-data/index.html'|href='/service/big-data'|g" "$FILE"
    sed -i "s|href='service/building-management-system/index.html'|href='/service/building-management-system'|g" "$FILE"
    sed -i "s|href='service/business-process-automation/index.html'|href='/service/business-process-automation'|g" "$FILE"
    sed -i "s|href='service/call-center-services/index.html'|href='/service/call-center-services'|g" "$FILE"
    sed -i "s|href='service/cctv-system/index.html'|href='/service/cctv-system'|g" "$FILE"
    sed -i "s|href='service/data-center-solutions-services/index.html'|href='/service/data-center-solutions-services'|g" "$FILE"
    sed -i "s|href='service/fire-alarm-fire-suspension-system/index.html'|href='/service/fire-alarm-fire-suspension-system'|g" "$FILE"
    sed -i "s|href='service/internet-of-things-iot/index.html'|href='/service/internet-of-things-iot'|g" "$FILE"
    sed -i "s|href='service/it-information-security/index.html'|href='/service/it-information-security'|g" "$FILE"
    sed -i "s|href='service/it-infrastructure-management/index.html'|href='/service/it-infrastructure-management'|g" "$FILE"
    sed -i "s|href='service/it-managed-services/index.html'|href='/service/it-managed-services'|g" "$FILE"
    sed -i "s|href='service/it-resource-outsourcing/index.html'|href='/service/it-resource-outsourcing'|g" "$FILE"
    sed -i "s|href='service/it-service-management/index.html'|href='/service/it-service-management'|g" "$FILE"
    sed -i "s|href='service/master-clock-system/index.html'|href='/service/master-clock-system'|g" "$FILE"
    sed -i "s|href='service/next-generation-data-centers/index.html'|href='/service/next-generation-data-centers'|g" "$FILE"
    sed -i "s|href='service/public-address-system/index.html'|href='/service/public-address-system'|g" "$FILE"
    sed -i "s|href='service/voice-over-ip-telephony-solutions-voip/index.html'|href='/service/voice-over-ip-telephony-solutions-voip'|g" "$FILE"
    sed -i "s|href='service/wireless-solutions/index.html'|href='/service/wireless-solutions'|g" "$FILE"
    sed -i "s|href='service/index.html'|href='/service'|g" "$FILE"
    sed -i "s|href='about/index.html'|href='/about'|g" "$FILE"
    sed -i "s|href='contact/index.html'|href='/contact'|g" "$FILE"
    sed -i "s|href='customers-clients/index.html'|href='/customers-clients'|g" "$FILE"
    sed -i "s|href='partners/index.html'|href='/partners'|g" "$FILE"
    sed -i "s|href='team-details/index.html'|href='/team-details'|g" "$FILE"
    sed -i "s|href='it-hardware-software/index.html'|href='/it-hardware-software'|g" "$FILE"
    sed -i "s|href='it-passive-equipment/index.html'|href='/it-passive-equipment'|g" "$FILE"
    sed -i "s|href='index.html'|href='/'|g" "$FILE"

    # 1-level relative ../something (double-quoted)
    sed -i 's|href="../service/access-control-system/index.html"|href="/service/access-control-system"|g' "$FILE"
    sed -i 's|href="../service/applications-development-services/index.html"|href="/service/applications-development-services"|g' "$FILE"
    sed -i 's|href="../service/artificial-intelligence-ai/index.html"|href="/service/artificial-intelligence-ai"|g' "$FILE"
    sed -i 's|href="../service/audio-visual-system/index.html"|href="/service/audio-visual-system"|g' "$FILE"
    sed -i 's|href="../service/big-data/index.html"|href="/service/big-data"|g' "$FILE"
    sed -i 's|href="../service/building-management-system/index.html"|href="/service/building-management-system"|g' "$FILE"
    sed -i 's|href="../service/business-process-automation/index.html"|href="/service/business-process-automation"|g' "$FILE"
    sed -i 's|href="../service/call-center-services/index.html"|href="/service/call-center-services"|g' "$FILE"
    sed -i 's|href="../service/cctv-system/index.html"|href="/service/cctv-system"|g' "$FILE"
    sed -i 's|href="../service/data-center-solutions-services/index.html"|href="/service/data-center-solutions-services"|g' "$FILE"
    sed -i 's|href="../service/fire-alarm-fire-suspension-system/index.html"|href="/service/fire-alarm-fire-suspension-system"|g' "$FILE"
    sed -i 's|href="../service/internet-of-things-iot/index.html"|href="/service/internet-of-things-iot"|g' "$FILE"
    sed -i 's|href="../service/it-information-security/index.html"|href="/service/it-information-security"|g' "$FILE"
    sed -i 's|href="../service/it-infrastructure-management/index.html"|href="/service/it-infrastructure-management"|g' "$FILE"
    sed -i 's|href="../service/it-managed-services/index.html"|href="/service/it-managed-services"|g' "$FILE"
    sed -i 's|href="../service/it-resource-outsourcing/index.html"|href="/service/it-resource-outsourcing"|g' "$FILE"
    sed -i 's|href="../service/it-service-management/index.html"|href="/service/it-service-management"|g' "$FILE"
    sed -i 's|href="../service/master-clock-system/index.html"|href="/service/master-clock-system"|g' "$FILE"
    sed -i 's|href="../service/next-generation-data-centers/index.html"|href="/service/next-generation-data-centers"|g' "$FILE"
    sed -i 's|href="../service/public-address-system/index.html"|href="/service/public-address-system"|g' "$FILE"
    sed -i 's|href="../service/voice-over-ip-telephony-solutions-voip/index.html"|href="/service/voice-over-ip-telephony-solutions-voip"|g' "$FILE"
    sed -i 's|href="../service/wireless-solutions/index.html"|href="/service/wireless-solutions"|g' "$FILE"
    sed -i 's|href="../service/index.html"|href="/service"|g' "$FILE"
    sed -i 's|href="../about/index.html"|href="/about"|g' "$FILE"
    sed -i 's|href="../contact/index.html"|href="/contact"|g' "$FILE"
    sed -i 's|href="../customers-clients/index.html"|href="/customers-clients"|g' "$FILE"
    sed -i 's|href="../partners/index.html"|href="/partners"|g' "$FILE"
    sed -i 's|href="../team-details/index.html"|href="/team-details"|g' "$FILE"
    sed -i 's|href="../it-hardware-software/index.html"|href="/it-hardware-software"|g' "$FILE"
    sed -i 's|href="../it-passive-equipment/index.html"|href="/it-passive-equipment"|g' "$FILE"
    sed -i 's|href="../index.html"|href="/"|g' "$FILE"

    # 1-level relative ../something (single-quoted)
    sed -i "s|href='../service/access-control-system/index.html'|href='/service/access-control-system'|g" "$FILE"
    sed -i "s|href='../service/applications-development-services/index.html'|href='/service/applications-development-services'|g" "$FILE"
    sed -i "s|href='../service/artificial-intelligence-ai/index.html'|href='/service/artificial-intelligence-ai'|g" "$FILE"
    sed -i "s|href='../service/audio-visual-system/index.html'|href='/service/audio-visual-system'|g" "$FILE"
    sed -i "s|href='../service/big-data/index.html'|href='/service/big-data'|g" "$FILE"
    sed -i "s|href='../service/building-management-system/index.html'|href='/service/building-management-system'|g" "$FILE"
    sed -i "s|href='../service/business-process-automation/index.html'|href='/service/business-process-automation'|g" "$FILE"
    sed -i "s|href='../service/call-center-services/index.html'|href='/service/call-center-services'|g" "$FILE"
    sed -i "s|href='../service/cctv-system/index.html'|href='/service/cctv-system'|g" "$FILE"
    sed -i "s|href='../service/data-center-solutions-services/index.html'|href='/service/data-center-solutions-services'|g" "$FILE"
    sed -i "s|href='../service/fire-alarm-fire-suspension-system/index.html'|href='/service/fire-alarm-fire-suspension-system'|g" "$FILE"
    sed -i "s|href='../service/internet-of-things-iot/index.html'|href='/service/internet-of-things-iot'|g" "$FILE"
    sed -i "s|href='../service/it-information-security/index.html'|href='/service/it-information-security'|g" "$FILE"
    sed -i "s|href='../service/it-infrastructure-management/index.html'|href='/service/it-infrastructure-management'|g" "$FILE"
    sed -i "s|href='../service/it-managed-services/index.html'|href='/service/it-managed-services'|g" "$FILE"
    sed -i "s|href='../service/it-resource-outsourcing/index.html'|href='/service/it-resource-outsourcing'|g" "$FILE"
    sed -i "s|href='../service/it-service-management/index.html'|href='/service/it-service-management'|g" "$FILE"
    sed -i "s|href='../service/master-clock-system/index.html'|href='/service/master-clock-system'|g" "$FILE"
    sed -i "s|href='../service/next-generation-data-centers/index.html'|href='/service/next-generation-data-centers'|g" "$FILE"
    sed -i "s|href='../service/public-address-system/index.html'|href='/service/public-address-system'|g" "$FILE"
    sed -i "s|href='../service/voice-over-ip-telephony-solutions-voip/index.html'|href='/service/voice-over-ip-telephony-solutions-voip'|g" "$FILE"
    sed -i "s|href='../service/wireless-solutions/index.html'|href='/service/wireless-solutions'|g" "$FILE"
    sed -i "s|href='../service/index.html'|href='/service'|g" "$FILE"
    sed -i "s|href='../about/index.html'|href='/about'|g" "$FILE"
    sed -i "s|href='../contact/index.html'|href='/contact'|g" "$FILE"
    sed -i "s|href='../customers-clients/index.html'|href='/customers-clients'|g" "$FILE"
    sed -i "s|href='../partners/index.html'|href='/partners'|g" "$FILE"
    sed -i "s|href='../team-details/index.html'|href='/team-details'|g" "$FILE"
    sed -i "s|href='../it-hardware-software/index.html'|href='/it-hardware-software'|g" "$FILE"
    sed -i "s|href='../it-passive-equipment/index.html'|href='/it-passive-equipment'|g" "$FILE"
    sed -i "s|href='../index.html'|href='/'|g" "$FILE"

    # 2-levels relative ../../something (double-quoted)
    sed -i 's|href="../../service/access-control-system/index.html"|href="/service/access-control-system"|g' "$FILE"
    sed -i 's|href="../../service/applications-development-services/index.html"|href="/service/applications-development-services"|g' "$FILE"
    sed -i 's|href="../../service/artificial-intelligence-ai/index.html"|href="/service/artificial-intelligence-ai"|g' "$FILE"
    sed -i 's|href="../../service/audio-visual-system/index.html"|href="/service/audio-visual-system"|g' "$FILE"
    sed -i 's|href="../../service/big-data/index.html"|href="/service/big-data"|g' "$FILE"
    sed -i 's|href="../../service/building-management-system/index.html"|href="/service/building-management-system"|g' "$FILE"
    sed -i 's|href="../../service/business-process-automation/index.html"|href="/service/business-process-automation"|g' "$FILE"
    sed -i 's|href="../../service/call-center-services/index.html"|href="/service/call-center-services"|g' "$FILE"
    sed -i 's|href="../../service/cctv-system/index.html"|href="/service/cctv-system"|g' "$FILE"
    sed -i 's|href="../../service/data-center-solutions-services/index.html"|href="/service/data-center-solutions-services"|g' "$FILE"
    sed -i 's|href="../../service/fire-alarm-fire-suspension-system/index.html"|href="/service/fire-alarm-fire-suspension-system"|g' "$FILE"
    sed -i 's|href="../../service/internet-of-things-iot/index.html"|href="/service/internet-of-things-iot"|g' "$FILE"
    sed -i 's|href="../../service/it-information-security/index.html"|href="/service/it-information-security"|g' "$FILE"
    sed -i 's|href="../../service/it-infrastructure-management/index.html"|href="/service/it-infrastructure-management"|g' "$FILE"
    sed -i 's|href="../../service/it-managed-services/index.html"|href="/service/it-managed-services"|g' "$FILE"
    sed -i 's|href="../../service/it-resource-outsourcing/index.html"|href="/service/it-resource-outsourcing"|g' "$FILE"
    sed -i 's|href="../../service/it-service-management/index.html"|href="/service/it-service-management"|g' "$FILE"
    sed -i 's|href="../../service/master-clock-system/index.html"|href="/service/master-clock-system"|g' "$FILE"
    sed -i 's|href="../../service/next-generation-data-centers/index.html"|href="/service/next-generation-data-centers"|g' "$FILE"
    sed -i 's|href="../../service/public-address-system/index.html"|href="/service/public-address-system"|g' "$FILE"
    sed -i 's|href="../../service/voice-over-ip-telephony-solutions-voip/index.html"|href="/service/voice-over-ip-telephony-solutions-voip"|g' "$FILE"
    sed -i 's|href="../../service/wireless-solutions/index.html"|href="/service/wireless-solutions"|g' "$FILE"
    sed -i 's|href="../../service/index.html"|href="/service"|g' "$FILE"
    sed -i 's|href="../../about/index.html"|href="/about"|g' "$FILE"
    sed -i 's|href="../../contact/index.html"|href="/contact"|g' "$FILE"
    sed -i 's|href="../../customers-clients/index.html"|href="/customers-clients"|g' "$FILE"
    sed -i 's|href="../../partners/index.html"|href="/partners"|g' "$FILE"
    sed -i 's|href="../../team-details/index.html"|href="/team-details"|g' "$FILE"
    sed -i 's|href="../../it-hardware-software/index.html"|href="/it-hardware-software"|g' "$FILE"
    sed -i 's|href="../../it-passive-equipment/index.html"|href="/it-passive-equipment"|g' "$FILE"
    sed -i 's|href="../../index.html"|href="/"|g' "$FILE"

    # 2-levels relative ../../something (single-quoted)
    sed -i "s|href='../../service/access-control-system/index.html'|href='/service/access-control-system'|g" "$FILE"
    sed -i "s|href='../../service/applications-development-services/index.html'|href='/service/applications-development-services'|g" "$FILE"
    sed -i "s|href='../../service/artificial-intelligence-ai/index.html'|href='/service/artificial-intelligence-ai'|g" "$FILE"
    sed -i "s|href='../../service/audio-visual-system/index.html'|href='/service/audio-visual-system'|g" "$FILE"
    sed -i "s|href='../../service/big-data/index.html'|href='/service/big-data'|g" "$FILE"
    sed -i "s|href='../../service/building-management-system/index.html'|href='/service/building-management-system'|g" "$FILE"
    sed -i "s|href='../../service/business-process-automation/index.html'|href='/service/business-process-automation'|g" "$FILE"
    sed -i "s|href='../../service/call-center-services/index.html'|href='/service/call-center-services'|g" "$FILE"
    sed -i "s|href='../../service/cctv-system/index.html'|href='/service/cctv-system'|g" "$FILE"
    sed -i "s|href='../../service/data-center-solutions-services/index.html'|href='/service/data-center-solutions-services'|g" "$FILE"
    sed -i "s|href='../../service/fire-alarm-fire-suspension-system/index.html'|href='/service/fire-alarm-fire-suspension-system'|g" "$FILE"
    sed -i "s|href='../../service/internet-of-things-iot/index.html'|href='/service/internet-of-things-iot'|g" "$FILE"
    sed -i "s|href='../../service/it-information-security/index.html'|href='/service/it-information-security'|g" "$FILE"
    sed -i "s|href='../../service/it-infrastructure-management/index.html'|href='/service/it-infrastructure-management'|g" "$FILE"
    sed -i "s|href='../../service/it-managed-services/index.html'|href='/service/it-managed-services'|g" "$FILE"
    sed -i "s|href='../../service/it-resource-outsourcing/index.html'|href='/service/it-resource-outsourcing'|g" "$FILE"
    sed -i "s|href='../../service/it-service-management/index.html'|href='/service/it-service-management'|g" "$FILE"
    sed -i "s|href='../../service/master-clock-system/index.html'|href='/service/master-clock-system'|g" "$FILE"
    sed -i "s|href='../../service/next-generation-data-centers/index.html'|href='/service/next-generation-data-centers'|g" "$FILE"
    sed -i "s|href='../../service/public-address-system/index.html'|href='/service/public-address-system'|g" "$FILE"
    sed -i "s|href='../../service/voice-over-ip-telephony-solutions-voip/index.html'|href='/service/voice-over-ip-telephony-solutions-voip'|g" "$FILE"
    sed -i "s|href='../../service/wireless-solutions/index.html'|href='/service/wireless-solutions'|g" "$FILE"
    sed -i "s|href='../../service/index.html'|href='/service'|g" "$FILE"
    sed -i "s|href='../../about/index.html'|href='/about'|g" "$FILE"
    sed -i "s|href='../../contact/index.html'|href='/contact'|g" "$FILE"
    sed -i "s|href='../../customers-clients/index.html'|href='/customers-clients'|g" "$FILE"
    sed -i "s|href='../../partners/index.html'|href='/partners'|g" "$FILE"
    sed -i "s|href='../../team-details/index.html'|href='/team-details'|g" "$FILE"
    sed -i "s|href='../../it-hardware-software/index.html'|href='/it-hardware-software'|g" "$FILE"
    sed -i "s|href='../../it-passive-equipment/index.html'|href='/it-passive-equipment'|g" "$FILE"
    sed -i "s|href='../../index.html'|href='/'|g" "$FILE"

    echo "  Done: $FILE"
}

# Root-level pages (depth=0)
echo "=== Processing root-level pages ==="
cp "${SRC}/index.html" "${DST}/home.blade.php" && apply_replacements "${DST}/home.blade.php" 0
cp "${SRC}/about/index.html" "${DST}/about.blade.php" && apply_replacements "${DST}/about.blade.php" 0
cp "${SRC}/contact/index.html" "${DST}/contact.blade.php" && apply_replacements "${DST}/contact.blade.php" 0
cp "${SRC}/customers-clients/index.html" "${DST}/customers-clients.blade.php" && apply_replacements "${DST}/customers-clients.blade.php" 0
cp "${SRC}/partners/index.html" "${DST}/partners.blade.php" && apply_replacements "${DST}/partners.blade.php" 0
cp "${SRC}/team-details/index.html" "${DST}/team-details.blade.php" && apply_replacements "${DST}/team-details.blade.php" 0
cp "${SRC}/it-hardware-software/index.html" "${DST}/it-hardware-software.blade.php" && apply_replacements "${DST}/it-hardware-software.blade.php" 0
cp "${SRC}/it-passive-equipment/index.html" "${DST}/it-passive-equipment.blade.php" && apply_replacements "${DST}/it-passive-equipment.blade.php" 0

# Service index (depth=1)
echo ""
echo "=== Processing service index ==="
cp "${SRC}/service/index.html" "${DST}/service/index.blade.php" && apply_replacements "${DST}/service/index.blade.php" 1

# Service sub-pages (depth=2)
echo ""
echo "=== Processing service sub-pages ==="
SERVICE_PAGES=(
    "access-control-system"
    "applications-development-services"
    "artificial-intelligence-ai"
    "audio-visual-system"
    "big-data"
    "building-management-system"
    "business-process-automation"
    "call-center-services"
    "cctv-system"
    "data-center-solutions-services"
    "fire-alarm-fire-suspension-system"
    "internet-of-things-iot"
    "it-information-security"
    "it-infrastructure-management"
    "it-managed-services"
    "it-resource-outsourcing"
    "it-service-management"
    "master-clock-system"
    "next-generation-data-centers"
    "public-address-system"
    "voice-over-ip-telephony-solutions-voip"
    "wireless-solutions"
)

for PAGE in "${SERVICE_PAGES[@]}"; do
    cp "${SRC}/service/${PAGE}/index.html" "${DST}/service/${PAGE}.blade.php" && apply_replacements "${DST}/service/${PAGE}.blade.php" 2
done

echo ""
echo "=== All blade views created! ==="
